server:
  port: ${PORT:0}

spring:
  application:
    name: DEPARTMENT-SERVICE
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format:
          sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: root
  cloud:
    config:
      name: department-service
app:
  description: this is being loaded in source code in application.yml